apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-transaction-config
data:
  application-k8s.properties: |
    management.endpoints.web.exposure.include=health,info,metrics,caches
    management.endpoint.health.show-details=always
    management.endpoint.health.probes.enabled=true
        
    spring.cache.type=caffeine
    spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=10m
   
    logging.level.root=INFO
    logging.level.com.example.bank=DEBUG
        
    server.tomcat.threads.max=200
    server.tomcat.threads.min=10
    server.tomcat.accept-count=100