apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-transaction-service
  labels:
    app: bank-transaction-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bank-transaction-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bank-transaction-service
    spec:
      containers:
        - name: bank-transaction-service
          image: bank-transaction-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"