apiVersion: v1
kind: Service
metadata:
  name: bank-transaction-service
spec:
  selector:
    app: bank-transaction-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer